### ISSUE TITLE
Watch mode creates infinite loop

### ISSUE THREAD

**Issue by TrySound** [blaugold/webpack-mocha-plugin#3]
https://github.com/TrySound/inferno-datagrid
```
yarn run start-test
```
and change any test

**Comment by blaugold** [comment]
As far as I can determine the problem seems to be that every time the coverage report is written to disk, webpack kicks of a new compilation which in turn runs the tests including coverage report. I thought webpack only watches files which are part of the dependency tree, so either that's not true or somehow coverage report files end up as dependencies.

You can exclude files from being watched, though. Addings this to the webpack config file solved it for me:

```javascript
watchOptions: {
    ignored: /coverage/
}
```

**Comment by TrySound** [comment]
Thanks a lot.
